# Generated by Django 4.2.27 on 2026-01-15 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('algorithm_type', models.CharField(max_length=20)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '排队中'), ('PROCESSING', 'AI处理中'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PENDING', max_length=20)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
